import type { Card } from "./types3v3v3";

// Support card data with all images from supoka folder
export const SAMPLE_CARDS: Card[] = [
  // SSR Cards (57 total)
  {
    id: "ssr1",
    name: "Air Shakur",
    rarity: "SSR",
    type: "wit",
    imageUrl: "./supoka/air-shakur-ssr-wit.png",
  },
  {
    id: "ssr2",
    name: "Bamboo Memory",
    rarity: "SSR",
    type: "power",
    imageUrl: "./supoka/bamboo-memory-ssr-power.png",
  },
  {
    id: "ssr3",
    name: "Biko Pegasus",
    rarity: "SSR",
    type: "speed",
    imageUrl: "./supoka/biko-pegasus-ssr-speed.png",
  },
  {
    id: "ssr4",
    name: "Curren Chan",
    rarity: "SSR",
    type: "wit",
    imageUrl: "./supoka/curren-chan-ssr-wit.png",
  },
  {
    id: "ssr5",
    name: "Daiwa Scarlet",
    rarity: "SSR",
    type: "power",
    imageUrl: "./supoka/daiwa-scarlet-ssr-power.png",
  },
  {
    id: "ssr6",
    name: "El Condor Pasa",
    rarity: "SSR",
    type: "power",
    imageUrl: "./supoka/el-condor-pasa-ssr-power.png",
  },
  {
    id: "ssr7",
    name: "Fine Motion",
    rarity: "SSR",
    type: "wit",
    imageUrl: "./supoka/fine-motion-ssr-wit.png",
  },
  {
    id: "ssr8",
    name: "Gold City",
    rarity: "SSR",
    type: "speed",
    imageUrl: "./supoka/gold-city-ssr-speed.png",
  },
  {
    id: "ssr9",
    name: "Gold Ship",
    rarity: "SSR",
    type: "speed",
    imageUrl: "./supoka/gold-ship-ssr-speed.png",
  },
  {
    id: "ssr10",
    name: "Gold Ship",
    rarity: "SSR",
    type: "stamina",
    imageUrl: "./supoka/gold-ship-ssr-stamina.png",
  },
  {
    id: "ssr11",
    name: "Grass Wonder",
    rarity: "SSR",
    type: "guts",
    imageUrl: "./supoka/grass-wonder-ssr-guts.png",
  },
  {
    id: "ssr12",
    name: "Haru Urara",
    rarity: "SSR",
    type: "guts",
    imageUrl: "./supoka/haru-urara-ssr-guts.png",
  },
  {
    id: "ssr13",
    name: "Hishi Akebono",
    rarity: "SSR",
    type: "guts",
    imageUrl: "./supoka/hishi-akebono-ssr-guts.png",
  },
  {
    id: "ssr14",
    name: "Ikuno Dictus",
    rarity: "SSR",
    type: "guts",
    imageUrl: "./supoka/ikuno-dictus-ssr-guts.png",
  },
  {
    id: "ssr15",
    name: "Ines Fujin",
    rarity: "SSR",
    type: "guts",
    imageUrl: "./supoka/ines-fujin-ssr-guts.png",
  },
  {
    id: "ssr16",
    name: "Kawakami Princess",
    rarity: "SSR",
    type: "speed",
    imageUrl: "./supoka/kawakami-princess-ssr-speed.png",
  },
  {
    id: "ssr17",
    name: "King Halo",
    rarity: "SSR",
    type: "power",
    imageUrl: "./supoka/king-halo-ssr-power.png",
  },
  {
    id: "ssr18",
    name: "Kitasan Black",
    rarity: "SSR",
    type: "speed",
    imageUrl: "./supoka/kitasan-black-ssr-speed.png",
  },
  {
    id: "ssr19",
    name: "Matikanetannhauser",
    rarity: "SSR",
    type: "guts",
    imageUrl: "./supoka/matikanetannhauser-ssr-guts.png",
  },
  {
    id: "ssr20",
    name: "Mejiro Dober",
    rarity: "SSR",
    type: "wit",
    imageUrl: "./supoka/mejiro-dober-ssr-wit.png",
  },
  {
    id: "ssr21",
    name: "Mejiro McQueen",
    rarity: "SSR",
    type: "stamina",
    imageUrl: "./supoka/mejiro-mcqueen-ssr-stamina.png",
  },
  {
    id: "ssr22",
    name: "Mejiro Palmer",
    rarity: "SSR",
    type: "guts",
    imageUrl: "./supoka/mejiro-palmer-ssr-guts.png",
  },
  {
    id: "ssr23",
    name: "Mejiro Ryan",
    rarity: "SSR",
    type: "guts",
    imageUrl: "./supoka/mejiro-ryan-ssr-guts.png",
  },
  {
    id: "ssr24",
    name: "Mihono Bourbon",
    rarity: "SSR",
    type: "wit",
    imageUrl: "./supoka/mihono-bourbon-ssr-wit.png",
  },
  {
    id: "ssr25",
    name: "Nakayama Festa",
    rarity: "SSR",
    type: "stamina",
    imageUrl: "./supoka/nakayama-festa-ssr-stamina.png",
  },
  {
    id: "ssr26",
    name: "Narita Brian",
    rarity: "SSR",
    type: "speed",
    imageUrl: "./supoka/narita-brian-ssr-speed.png",
  },
  {
    id: "ssr27",
    name: "Narita Brian",
    rarity: "SSR",
    type: "stamina",
    imageUrl: "./supoka/narita-brian-ssr-stamina.png",
  },
  {
    id: "ssr28",
    name: "Nice Nature",
    rarity: "SSR",
    type: "wit",
    imageUrl: "./supoka/nice-nature-ssr-wit.png",
  },
  {
    id: "ssr29",
    name: "Nishino Flower",
    rarity: "SSR",
    type: "speed",
    imageUrl: "./supoka/nishino-flower-ssr-speed.png",
  },
  {
    id: "ssr30",
    name: "Oguri Cap",
    rarity: "SSR",
    type: "power",
    imageUrl: "./supoka/oguri-cap-ssr-power.png",
  },
  {
    id: "ssr31",
    name: "Rice Shower",
    rarity: "SSR",
    type: "power",
    imageUrl: "./supoka/rice-shower-ssr-power.png",
  },
  {
    id: "ssr32",
    name: "Rice Shower",
    rarity: "SSR",
    type: "stamina",
    imageUrl: "./supoka/rice-shower-ssr-stamina.png",
  },
  {
    id: "ssr33",
    name: "Riko Kashimoto",
    rarity: "SSR",
    type: "friend",
    imageUrl: "./supoka/riko-kashimoto-ssr-friend.png",
  },
  {
    id: "ssr34",
    name: "Sakura Bakushin O",
    rarity: "SSR",
    type: "speed",
    imageUrl: "./supoka/sakura-bakushin-o-ssr-speed.png",
  },
  {
    id: "ssr35",
    name: "Sakura Chiyono O",
    rarity: "SSR",
    type: "stamina",
    imageUrl: "./supoka/sakura-chiyono-o-ssr-stamina.png",
  },
  {
    id: "ssr36",
    name: "Satono Diamond",
    rarity: "SSR",
    type: "stamina",
    imageUrl: "./supoka/satono-diamond-ssr-stamina.png",
  },
  {
    id: "ssr37",
    name: "Seiun Sky",
    rarity: "SSR",
    type: "stamina",
    imageUrl: "./supoka/seiun-sky-ssr-stamina.png",
  },
  {
    id: "ssr38",
    name: "Seiun Sky",
    rarity: "SSR",
    type: "wit",
    imageUrl: "./supoka/seiun-sky-ssr-wit.png",
  },
  {
    id: "ssr39",
    name: "Silence Suzuka",
    rarity: "SSR",
    type: "speed",
    imageUrl: "./supoka/silence-suzuka-ssr-speed.png",
  },
  {
    id: "ssr40",
    name: "Silence Suzuka",
    rarity: "SSR",
    type: "stamina",
    imageUrl: "./supoka/silence-suzuka-ssr-stamina.png",
  },
  {
    id: "ssr41",
    name: "Smart Falcon",
    rarity: "SSR",
    type: "power",
    imageUrl: "./supoka/smart-falcon-ssr-power.png",
  },
  {
    id: "ssr42",
    name: "Special Week",
    rarity: "SSR",
    type: "guts",
    imageUrl: "./supoka/special-week-ssr-guts.png",
  },
  {
    id: "ssr43",
    name: "Special Week",
    rarity: "SSR",
    type: "speed",
    imageUrl: "./supoka/special-week-ssr-speed.png",
  },
  {
    id: "ssr44",
    name: "Super Creek",
    rarity: "SSR",
    type: "stamina",
    imageUrl: "./supoka/super-creek-ssr-stamina.png",
  },
  {
    id: "ssr45",
    name: "Sweep Tosho",
    rarity: "SSR",
    type: "speed",
    imageUrl: "./supoka/sweep-tosho-ssr-speed.png",
  },
  {
    id: "ssr46",
    name: "Tamamo Cross",
    rarity: "SSR",
    type: "power",
    imageUrl: "./supoka/tamamo-cross-ssr-power.png",
  },
  {
    id: "ssr47",
    name: "Tamamo Cross",
    rarity: "SSR",
    type: "stamina",
    imageUrl: "./supoka/tamamo-cross-ssr-stamina.png",
  },
  {
    id: "ssr48",
    name: "Tazuna Hayakawa",
    rarity: "SSR",
    type: "friend",
    imageUrl: "./supoka/tazuna-hayakawa-ssr-friend.png",
  },
  {
    id: "ssr49",
    name: "Tokai Teio",
    rarity: "SSR",
    type: "speed",
    imageUrl: "./supoka/tokai-teio-ssr-speed.png",
  },
  {
    id: "ssr50",
    name: "Twin Turbo",
    rarity: "SSR",
    type: "speed",
    imageUrl: "./supoka/twin-turbo-ssr-speed.png",
  },
  {
    id: "ssr51",
    name: "Vodka",
    rarity: "SSR",
    type: "power",
    imageUrl: "./supoka/vodka-ssr-power.png",
  },
  {
    id: "ssr52",
    name: "Winning Ticket",
    rarity: "SSR",
    type: "guts",
    imageUrl: "./supoka/winning-ticket-ssr-guts.png",
  },
  {
    id: "ssr53",
    name: "Winning Ticket",
    rarity: "SSR",
    type: "power",
    imageUrl: "./supoka/winning-ticket-ssr-power.png",
  },
  {
    id: "ssr54",
    name: "Winning Ticket",
    rarity: "SSR",
    type: "stamina",
    imageUrl: "./supoka/winning-ticket-ssr-stamina.png",
  },
  {
    id: "ssr55",
    name: "Yaeno Muteki",
    rarity: "SSR",
    type: "power",
    imageUrl: "./supoka/yaeno-muteki-ssr-power.png",
  },
  {
    id: "ssr56",
    name: "Yukino Bijin",
    rarity: "SSR",
    type: "guts",
    imageUrl: "./supoka/yukino-bijin-ssr-guts.png",
  },
  {
    id: "ssr57",
    name: "Yukino Bijin",
    rarity: "SSR",
    type: "wit",
    imageUrl: "./supoka/yukino-bijin-ssr-wit.png",
  },
  {
    id: "ssr58",
    name: "Zenno Rob Roy",
    rarity: "SSR",
    type: "speed",
    imageUrl: "./supoka/zenno-rob-roy-ssr-speed.png",
  },
  {
    id: "ssr59",
    name: "Daitaku Helios",
    rarity: "SSR",
    type: "power",
    imageUrl: "./supoka/daitaku-helios-ssr-power.png",
  },
  {
    id: "ssr60",
    name: "Marvelous Sunday",
    rarity: "SSR",
    type: "power",
    imageUrl: "./supoka/marvelous-sunday-ssr-power.png",
  },
  {
    id: "ssr61",
    name: "Narita Taishin",
    rarity: "SSR",
    type: "wit",
    imageUrl: "./supoka/narita-taishin-ssr-wit.png",
  },
  {
    id: "ssr62",
    name: "Mayano Top Gun",
    rarity: "SSR",
    type: "speed",
    imageUrl: "./supoka/mayano-top-gun-ssr-speed.png",
  },

  // SR Cards (36 total)
  {
    id: "sr1",
    name: "Agnes Digital",
    rarity: "SR",
    type: "power",
    imageUrl: "./supoka/agnes-digital-sr-power.png",
  },
  {
    id: "sr2",
    name: "Agnes Tachyon",
    rarity: "SR",
    type: "wit",
    imageUrl: "./supoka/agnes-tachyon-sr-wit.png",
  },
  {
    id: "sr3",
    name: "Air Groove",
    rarity: "SR",
    type: "guts",
    imageUrl: "./supoka/air-groove-sr-guts.png",
  },
  {
    id: "sr4",
    name: "Aoi Kiryuin",
    rarity: "SR",
    type: "friend",
    imageUrl: "./supoka/aoi-kiryuin-sr-friend.png",
  },
  {
    id: "sr5",
    name: "Biwa Hayahide",
    rarity: "SR",
    type: "power",
    imageUrl: "./supoka/biwa-hayahide-sr-power.png",
  },
  {
    id: "sr6",
    name: "Daitaku Helios",
    rarity: "SR",
    type: "power",
    imageUrl: "./supoka/daitaku-helios-sr-power.png",
  },
  {
    id: "sr7",
    name: "Daiwa Scarlet",
    rarity: "SR",
    type: "wit",
    imageUrl: "./supoka/daiwa-scarlet-sr-wit.png",
  },
  {
    id: "sr8",
    name: "Eishin Flash",
    rarity: "SR",
    type: "speed",
    imageUrl: "./supoka/eishin-flash-sr-speed.png",
  },
  {
    id: "sr9",
    name: "Fine Motion",
    rarity: "SR",
    type: "power",
    imageUrl: "./supoka/fine-motion-sr-power.png",
  },
  {
    id: "sr10",
    name: "Fuji Kiseki",
    rarity: "SR",
    type: "wit",
    imageUrl: "./supoka/fuji-kiseki-sr-wit.png",
  },
  {
    id: "sr11",
    name: "Hishi Amazon",
    rarity: "SR",
    type: "power",
    imageUrl: "./supoka/hishi-amazon-sr-power.png",
  },
  {
    id: "sr12",
    name: "Ikuno Dictus",
    rarity: "SR",
    type: "wit",
    imageUrl: "./supoka/ikuno-dictus-sr-wit.png",
  },
  {
    id: "sr13",
    name: "King Halo",
    rarity: "SR",
    type: "speed",
    imageUrl: "./supoka/king-halo-sr-speed.png",
  },
  {
    id: "sr14",
    name: "Manhattan Cafe",
    rarity: "SR",
    type: "stamina",
    imageUrl: "./supoka/manhattan-cafe-sr-stamina.png",
  },
  {
    id: "sr15",
    name: "Marvelous Sunday",
    rarity: "SR",
    type: "wit",
    imageUrl: "./supoka/marvelous-sunday-sr-wit.png",
  },
  {
    id: "sr16",
    name: "Matifuku",
    rarity: "SR",
    type: "wit",
    imageUrl: "./supoka/matikanefukukitaru-sr-wit.png",
  },
  {
    id: "sr17",
    name: "Mayano Top Gun",
    rarity: "SR",
    type: "stamina",
    imageUrl: "./supoka/mayano-top-gun-sr-stamina.png",
  },
  {
    id: "sr18",
    name: "Meisho Doto",
    rarity: "SR",
    type: "guts",
    imageUrl: "./supoka/meisho-doto-sr-guts.png",
  },
  {
    id: "sr19",
    name: "Mejiro Ardan",
    rarity: "SR",
    type: "wit",
    imageUrl: "./supoka/mejiro-ardan-sr-wit.png",
  },
  {
    id: "sr20",
    name: "Mejiro Dober",
    rarity: "SR",
    type: "wit",
    imageUrl: "./supoka/mejiro-dober-sr-wit.png",
  },
  {
    id: "sr21",
    name: "Mejiro Ryan",
    rarity: "SR",
    type: "power",
    imageUrl: "./supoka/mejiro-ryan-sr-power.png",
  },
  {
    id: "sr22",
    name: "Mihono Bourbon",
    rarity: "SR",
    type: "power",
    imageUrl: "./supoka/mihono-bourbon-sr-power.png",
  },
  {
    id: "sr23",
    name: "Narita Taishin",
    rarity: "SR",
    type: "speed",
    imageUrl: "./supoka/narita-taishin-sr-speed.png",
  },
  {
    id: "sr24",
    name: "Nice Nature",
    rarity: "SR",
    type: "guts",
    imageUrl: "./supoka/nice-nature-sr-guts.png",
  },
  {
    id: "sr25",
    name: "Nice Nature",
    rarity: "SR",
    type: "wit",
    imageUrl: "./supoka/nice-nature-sr-wit.png",
  },
  {
    id: "sr26",
    name: "Nishino Flower",
    rarity: "SR",
    type: "power",
    imageUrl: "./supoka/nishino-flower-sr-power.png",
  },
  {
    id: "sr27",
    name: "Seeking the Pearl",
    rarity: "SR",
    type: "guts",
    imageUrl: "./supoka/seeking-the-pearl-sr-guts.png",
  },
  {
    id: "sr28",
    name: "Shinko Windy",
    rarity: "SR",
    type: "speed",
    imageUrl: "./supoka/shinko-windy-sr-speed.png",
  },
  {
    id: "sr29",
    name: "Sirius Symboli",
    rarity: "SR",
    type: "guts",
    imageUrl: "./supoka/sirius-symboli-sr-guts.png",
  },
  {
    id: "sr30",
    name: "Sweep Tosho",
    rarity: "SR",
    type: "speed",
    imageUrl: "./supoka/sweep-tosho-sr-speed.png",
  },
  {
    id: "sr31",
    name: "Tosen Jordan",
    rarity: "SR",
    type: "stamina",
    imageUrl: "./supoka/tosen-jordan-sr-stamina.png",
  },
  {
    id: "sr32",
    name: "Yukino Bijin",
    rarity: "SR",
    type: "guts",
    imageUrl: "./supoka/yukino-bijin-sr-guts.png",
  },
  {
    id: "sr33",
    name: "Zenno Rob Roy",
    rarity: "SR",
    type: "stamina",
    imageUrl: "./supoka/zenno-rob-roy-sr-stamina.png",
  },
  {
    id: "sr34",
    name: "Vodka",
    rarity: "SR",
    type: "speed",
    imageUrl: "./supoka/vodka-sr-speed.png",
  },

  // R Cards (73 total)
  {
    id: "r1",
    name: "Agnes Digital",
    rarity: "R",
    type: "power",
    imageUrl: "./supoka/agnes-digital-r-power.png",
  },
  {
    id: "r2",
    name: "Agnes Tachyon",
    rarity: "R",
    type: "wit",
    imageUrl: "./supoka/agnes-tachyon-r-wit.png",
  },
  {
    id: "r3",
    name: "Air Groove",
    rarity: "R",
    type: "guts",
    imageUrl: "./supoka/air-groove-r-guts.png",
  },
  {
    id: "r4",
    name: "Air Shakur",
    rarity: "R",
    type: "wit",
    imageUrl: "./supoka/air-shakur-r-wit.png",
  },
  {
    id: "r5",
    name: "Aoi Kiryuin",
    rarity: "R",
    type: "friend",
    imageUrl: "./supoka/aoi-kiryuin-r-friend.png",
  },
  {
    id: "r6",
    name: "Bamboo Memory",
    rarity: "R",
    type: "power",
    imageUrl: "./supoka/bamboo-memory-r-power.png",
  },
  {
    id: "r7",
    name: "Biko Pegasus",
    rarity: "R",
    type: "speed",
    imageUrl: "./supoka/biko-pegasus-r-speed.png",
  },
  {
    id: "r8",
    name: "Biwa Hayahide",
    rarity: "R",
    type: "power",
    imageUrl: "./supoka/biwa-hayahide-r-power.png",
  },
  {
    id: "r9",
    name: "Curren Chan",
    rarity: "R",
    type: "wit",
    imageUrl: "./supoka/curren-chan-r-wit.png",
  },
  {
    id: "r10",
    name: "Daitaku Helios",
    rarity: "R",
    type: "power",
    imageUrl: "./supoka/daitaku-helios-r-power.png",
  },
  {
    id: "r11",
    name: "Daiwa Scarlet",
    rarity: "R",
    type: "wit",
    imageUrl: "./supoka/daiwa-scarlet-r-wit.png",
  },
  {
    id: "r12",
    name: "Eishin Flash",
    rarity: "R",
    type: "speed",
    imageUrl: "./supoka/eishin-flash-r-speed.png",
  },
  {
    id: "r13",
    name: "El Condor Pasa",
    rarity: "R",
    type: "power",
    imageUrl: "./supoka/el-condor-pasa-r-power.png",
  },
  {
    id: "r14",
    name: "Fine Motion",
    rarity: "R",
    type: "wit",
    imageUrl: "./supoka/fine-motion-r-wit.png",
  },
  {
    id: "r15",
    name: "Fuji Kiseki",
    rarity: "R",
    type: "wit",
    imageUrl: "./supoka/fuji-kiseki-r-wit.png",
  },
  {
    id: "r16",
    name: "Gold City",
    rarity: "R",
    type: "speed",
    imageUrl: "./supoka/gold-city-r-speed.png",
  },
  {
    id: "r17",
    name: "Gold Ship",
    rarity: "R",
    type: "stamina",
    imageUrl: "./supoka/gold-ship-r-stamina.png",
  },
  {
    id: "r18",
    name: "Grass Wonder",
    rarity: "R",
    type: "guts",
    imageUrl: "./supoka/grass-wonder-r-guts.png",
  },
  {
    id: "r19",
    name: "Haru Urara",
    rarity: "R",
    type: "guts",
    imageUrl: "./supoka/haru-urara-r-guts.png",
  },
  {
    id: "r20",
    name: "Hishi Akebono",
    rarity: "R",
    type: "guts",
    imageUrl: "./supoka/hishi-akebono-r-guts.png",
  },
  {
    id: "r21",
    name: "Hishi Amazon",
    rarity: "R",
    type: "power",
    imageUrl: "./supoka/hishi-amazon-r-power.png",
  },
  {
    id: "r22",
    name: "Ikuno Dictus",
    rarity: "R",
    type: "wit",
    imageUrl: "./supoka/ikuno-dictus-r-wit.png",
  },
  {
    id: "r23",
    name: "Ines Fujin",
    rarity: "R",
    type: "guts",
    imageUrl: "./supoka/ines-fujin-r-guts.png",
  },
  {
    id: "r24",
    name: "Kawakami Princess",
    rarity: "R",
    type: "speed",
    imageUrl: "./supoka/kawakami-princess-r-speed.png",
  },
  {
    id: "r25",
    name: "King Halo",
    rarity: "R",
    type: "speed",
    imageUrl: "./supoka/king-halo-r-speed.png",
  },
  {
    id: "r26",
    name: "Kitasan Black",
    rarity: "R",
    type: "speed",
    imageUrl: "./supoka/kitasan-black-r-speed.png",
  },
  {
    id: "r27",
    name: "Manhattan Cafe",
    rarity: "R",
    type: "stamina",
    imageUrl: "./supoka/manhattan-cafe-r-stamina.png",
  },
  {
    id: "r28",
    name: "Maruzensky",
    rarity: "R",
    type: "speed",
    imageUrl: "./supoka/maruzensky-r-speed.png",
  },
  {
    id: "r29",
    name: "Marvelous Sunday",
    rarity: "R",
    type: "wit",
    imageUrl: "./supoka/marvelous-sunday-r-wit.png",
  },
  {
    id: "r30",
    name: "Matifuku",
    rarity: "R",
    type: "wit",
    imageUrl: "./supoka/matikanefukukitaru-r-wit.png",
  },
  {
    id: "r31",
    name: "Matikanetannhauser",
    rarity: "R",
    type: "guts",
    imageUrl: "./supoka/matikanetannhauser-r-guts.png",
  },
  {
    id: "r32",
    name: "Mayano Top Gun",
    rarity: "R",
    type: "stamina",
    imageUrl: "./supoka/mayano-top-gun-r-stamina.png",
  },
  {
    id: "r33",
    name: "Meisho Doto",
    rarity: "R",
    type: "guts",
    imageUrl: "./supoka/meisho-doto-r-guts.png",
  },
  {
    id: "r34",
    name: "Mejiro Ardan",
    rarity: "R",
    type: "wit",
    imageUrl: "./supoka/mejiro-ardan-r-wit.png",
  },
  {
    id: "r35",
    name: "Mejiro Dober",
    rarity: "R",
    type: "wit",
    imageUrl: "./supoka/mejiro-dober-r-wit.png",
  },
  {
    id: "r36",
    name: "Mejiro McQueen",
    rarity: "R",
    type: "stamina",
    imageUrl: "./supoka/mejiro-mcqueen-r-stamina.png",
  },
  {
    id: "r37",
    name: "Mejiro Palmer",
    rarity: "R",
    type: "guts",
    imageUrl: "./supoka/mejiro-palmer-r-guts.png",
  },
  {
    id: "r38",
    name: "Mejiro Ryan",
    rarity: "R",
    type: "power",
    imageUrl: "./supoka/mejiro-ryan-r-power.png",
  },
  {
    id: "r39",
    name: "Mihono Bourbon",
    rarity: "R",
    type: "power",
    imageUrl: "./supoka/mihono-bourbon-r-power.png",
  },
  {
    id: "r40",
    name: "Nakayama Festa",
    rarity: "R",
    type: "stamina",
    imageUrl: "./supoka/nakayama-festa-r-stamina.png",
  },
  {
    id: "r41",
    name: "Narita Brian",
    rarity: "R",
    type: "speed",
    imageUrl: "./supoka/narita-brian-r-speed.png",
  },
  {
    id: "r42",
    name: "Narita Taishin",
    rarity: "R",
    type: "speed",
    imageUrl: "./supoka/narita-taishin-r-speed.png",
  },
  {
    id: "r43",
    name: "Nice Nature",
    rarity: "R",
    type: "guts",
    imageUrl: "./supoka/nice-nature-r-guts.png",
  },
  {
    id: "r44",
    name: "Nishino Flower",
    rarity: "R",
    type: "speed",
    imageUrl: "./supoka/nishino-flower-r-speed.png",
  },
  {
    id: "r45",
    name: "Oguri Cap",
    rarity: "R",
    type: "power",
    imageUrl: "./supoka/oguri-cap-r-power.png",
  },
  {
    id: "r46",
    name: "Rice Shower",
    rarity: "R",
    type: "stamina",
    imageUrl: "./supoka/rice-shower-r-stamina.png",
  },
  {
    id: "r47",
    name: "Riko Kashimoto",
    rarity: "R",
    type: "friend",
    imageUrl: "./supoka/riko-kashimoto-r-friend.png",
  },
  {
    id: "r48",
    name: "Sakura Bakushin O",
    rarity: "R",
    type: "speed",
    imageUrl: "./supoka/sakura-bakushin-o-r-speed.png",
  },
  {
    id: "r49",
    name: "Sakura Chiyono O",
    rarity: "R",
    type: "stamina",
    imageUrl: "./supoka/sakura-chiyono-o-r-stamina.png",
  },
  {
    id: "r50",
    name: "Satono Diamond",
    rarity: "R",
    type: "stamina",
    imageUrl: "./supoka/satono-diamond-r-stamina.png",
  },
  {
    id: "r51",
    name: "Seeking the Pearl",
    rarity: "R",
    type: "guts",
    imageUrl: "./supoka/seeking-the-pearl-r-guts.png",
  },
  {
    id: "r52",
    name: "Seiun Sky",
    rarity: "R",
    type: "stamina",
    imageUrl: "./supoka/seiun-sky-r-stamina.png",
  },
  {
    id: "r53",
    name: "Shinko Windy",
    rarity: "R",
    type: "speed",
    imageUrl: "./supoka/shinko-windy-r-speed.png",
  },
  {
    id: "r54",
    name: "Silence Suzuka",
    rarity: "R",
    type: "speed",
    imageUrl: "./supoka/silence-suzuka-r-speed.png",
  },
  {
    id: "r55",
    name: "Sirius Symboli",
    rarity: "R",
    type: "guts",
    imageUrl: "./supoka/sirius-symboli-r-guts.png",
  },
  {
    id: "r56",
    name: "Smart Falcon",
    rarity: "R",
    type: "power",
    imageUrl: "./supoka/smart-falcon-r-power.png",
  },
  {
    id: "r57",
    name: "Special Week",
    rarity: "R",
    type: "guts",
    imageUrl: "./supoka/special-week-r-guts.png",
  },
  {
    id: "r58",
    name: "Super Creek",
    rarity: "R",
    type: "stamina",
    imageUrl: "./supoka/super-creek-r-stamina.png",
  },
  {
    id: "r59",
    name: "Sweep Tosho",
    rarity: "R",
    type: "speed",
    imageUrl: "./supoka/sweep-tosho-r-speed.png",
  },
  {
    id: "r60",
    name: "Symboli Rudolf",
    rarity: "R",
    type: "wit",
    imageUrl: "./supoka/symboli-rudolf-r-wit.png",
  },
  {
    id: "r61",
    name: "Taiki Shuttle",
    rarity: "R",
    type: "speed",
    imageUrl: "./supoka/taiki-shuttle-r-speed.png",
  },
  {
    id: "r62",
    name: "Tamamo Cross",
    rarity: "R",
    type: "stamina",
    imageUrl: "./supoka/tamamo-cross-r-stamina.png",
  },
  {
    id: "r63",
    name: "Tazuna Hayakawa",
    rarity: "R",
    type: "friend",
    imageUrl: "./supoka/tazuna-hayakawa-r-friend.png",
  },
  {
    id: "r64",
    name: "TM Opera O",
    rarity: "R",
    type: "stamina",
    imageUrl: "./supoka/tm-opera-o-r-stamina.png",
  },
  {
    id: "r65",
    name: "Tokai Teio",
    rarity: "R",
    type: "speed",
    imageUrl: "./supoka/tokai-teio-r-speed.png",
  },
  {
    id: "r66",
    name: "Tosen Jordan",
    rarity: "R",
    type: "stamina",
    imageUrl: "./supoka/tosen-jordan-r-stamina.png",
  },
  {
    id: "r67",
    name: "Twin Turbo",
    rarity: "R",
    type: "speed",
    imageUrl: "./supoka/twin-turbo-r-speed.png",
  },
  {
    id: "r68",
    name: "Vodka",
    rarity: "R",
    type: "power",
    imageUrl: "./supoka/vodka-r-power.png",
  },
  {
    id: "r69",
    name: "Winning Ticket",
    rarity: "R",
    type: "guts",
    imageUrl: "./supoka/winning-ticket-r-guts.png",
  },
  {
    id: "r70",
    name: "Yaeno Muteki",
    rarity: "R",
    type: "power",
    imageUrl: "./supoka/yaeno-muteki-r-power.png",
  },
  {
    id: "r71",
    name: "Yukino Bijin",
    rarity: "R",
    type: "guts",
    imageUrl: "./supoka/yukino-bijin-r-guts.png",
  },
  {
    id: "r72",
    name: "Zenno Rob Roy",
    rarity: "R",
    type: "stamina",
    imageUrl: "./supoka/zenno-rob-roy-r-stamina.png",
  },
];
