import type { UmaMusume, Map } from "./types";

// All available Uma Musume in global version
export const SAMPLE_UMAS: UmaMusume[] = [
  {
    id: "1",
    name: "Tosen Jordan",
    imageUrl: "./uma-portraits/tosen-jordan.png",
  },
  {
    id: "2",
    name: "Symboli Rudolf (Festival)",
    imageUrl: "./uma-portraits/symboli-rudolf-festival.png",
  },
  {
    id: "3",
    name: "Gold City (Festival)",
    imageUrl: "./uma-portraits/gold-city-festival.png",
  },
  {
    id: "4",
    name: "Manhattan Cafe",
    imageUrl: "./uma-portraits/manhattan-cafe.png",
  },
  {
    id: "5",
    name: "Kawakami Princess",
    imageUrl: "./uma-portraits/kawakami-princess.png",
  },
  {
    id: "6",
    name: "Rice Shower (Halloween)",
    imageUrl: "./uma-portraits/rice-shower-halloween.png",
  },
  {
    id: "7",
    name: "Super Creek (Halloween)",
    imageUrl: "./uma-portraits/super-creek-halloween.png",
  },
  {
    id: "8",
    name: "Agnes Digital",
    imageUrl: "./uma-portraits/agnes-digital.png",
  },
  {
    id: "9",
    name: "Hishi Akebono",
    imageUrl: "./uma-portraits/hishi-akebono.png",
  },
  {
    id: "10",
    name: "Matifuku (Full Armor)",
    imageUrl: "./uma-portraits/matikanefukukitaru-fullarmor.png",
  },
  {
    id: "11",
    name: "Eishin Flash",
    imageUrl: "./uma-portraits/eishin-flash.png",
  },
  {
    id: "12",
    name: "Meisho Doto",
    imageUrl: "./uma-portraits/meisho-doto.png",
  },
  {
    id: "13",
    name: "Special Week (Summer)",
    imageUrl: "./uma-portraits/special-week-summer.png",
  },
  {
    id: "14",
    name: "Maruzensky (Summer)",
    imageUrl: "./uma-portraits/maruzensky-summer.png",
  },
  { id: "15", name: "Gold City", imageUrl: "./uma-portraits/gold-city.png" },
  {
    id: "16",
    name: "Fuji Kiseki",
    imageUrl: "./uma-portraits/fuji-kiseki.png",
  },
  {
    id: "17",
    name: "Grass Wonder (Fantasy)",
    imageUrl: "./uma-portraits/grass-wonder-fantasy.png",
  },
  {
    id: "18",
    name: "El Condor Pasa (Fantasy)",
    imageUrl: "./uma-portraits/el-condor-pasa-fantasy.png",
  },
  {
    id: "19",
    name: "Hishi Amazon",
    imageUrl: "./uma-portraits/hishi-amazon.png",
  },
  { id: "20", name: "Seiun Sky", imageUrl: "./uma-portraits/seiun-sky.png" },
  {
    id: "21",
    name: "Air Groove (Wedding)",
    imageUrl: "./uma-portraits/air-groove-wedding.png",
  },
  {
    id: "22",
    name: "Mayano Top Gun (Wedding)",
    imageUrl: "./uma-portraits/mayano-top-gun-wedding.png",
  },
  {
    id: "23",
    name: "Narita Brian",
    imageUrl: "./uma-portraits/narita-brian.png",
  },
  {
    id: "24",
    name: "Smart Falcon",
    imageUrl: "./uma-portraits/smart-falcon.png",
  },
  {
    id: "25",
    name: "Narita Taishin",
    imageUrl: "./uma-portraits/narita-taishin.png",
  },
  {
    id: "26",
    name: "Curren Chan",
    imageUrl: "./uma-portraits/curren-chan.png",
  },
  {
    id: "27",
    name: "Tokai Teio (Anime Collab)",
    imageUrl: "./uma-portraits/tokai-teio-anime.png",
  },
  {
    id: "28",
    name: "Mejiro McQueen (Anime Collab)",
    imageUrl: "./uma-portraits/mejiro-mcqueen-anime.png",
  },
  {
    id: "29",
    name: "Biwa Hayahide",
    imageUrl: "./uma-portraits/biwa-hayahide.png",
  },
  {
    id: "30",
    name: "Mihono Bourbon",
    imageUrl: "./uma-portraits/mihono-bourbon.png",
  },
  { id: "31", name: "TM Opera O", imageUrl: "./uma-portraits/tm-opera-o.png" },
  {
    id: "32",
    name: "Special Week",
    imageUrl: "./uma-portraits/special-week.png",
  },
  {
    id: "33",
    name: "Silence Suzuka",
    imageUrl: "./uma-portraits/silence-suzuka.png",
  },
  { id: "34", name: "Tokai Teio", imageUrl: "./uma-portraits/tokai-teio.png" },
  { id: "35", name: "Maruzensky", imageUrl: "./uma-portraits/maruzensky.png" },
  { id: "36", name: "Oguri Cap", imageUrl: "./uma-portraits/oguri-cap.png" },
  {
    id: "37",
    name: "Taiki Shuttle",
    imageUrl: "./uma-portraits/taiki-shuttle.png",
  },
  {
    id: "38",
    name: "Mejiro McQueen",
    imageUrl: "./uma-portraits/mejiro-mcqueen.png",
  },
  {
    id: "39",
    name: "Symboli Rudolf",
    imageUrl: "./uma-portraits/symboli-rudolf.png",
  },
  {
    id: "40",
    name: "Rice Shower",
    imageUrl: "./uma-portraits/rice-shower.png",
  },
  { id: "41", name: "Gold Ship", imageUrl: "./uma-portraits/gold-ship.png" },
  { id: "42", name: "Vodka", imageUrl: "./uma-portraits/vodka.png" },
  {
    id: "43",
    name: "Daiwa Scarlet",
    imageUrl: "./uma-portraits/daiwa-scarlet.png",
  },
  {
    id: "44",
    name: "Grass Wonder",
    imageUrl: "./uma-portraits/grass-wonder.png",
  },
  {
    id: "45",
    name: "El Condor Pasa",
    imageUrl: "./uma-portraits/el-condor-pasa.png",
  },
  { id: "46", name: "Air Groove", imageUrl: "./uma-portraits/air-groove.png" },
  {
    id: "47",
    name: "Mayano Top Gun",
    imageUrl: "./uma-portraits/mayano-top-gun.png",
  },
  {
    id: "48",
    name: "Super Creek",
    imageUrl: "./uma-portraits/super-creek.png",
  },
  {
    id: "49",
    name: "Mejiro Ryan",
    imageUrl: "./uma-portraits/mejiro-ryan.png",
  },
  {
    id: "50",
    name: "Agnes Tachyon",
    imageUrl: "./uma-portraits/agnes-tachyon.png",
  },
  {
    id: "51",
    name: "Winning Ticket",
    imageUrl: "./uma-portraits/winning-ticket.png",
  },
  {
    id: "52",
    name: "Sakura Bakushin O",
    imageUrl: "./uma-portraits/sakura-bakushin-o.png",
  },
  { id: "53", name: "Haru Urara", imageUrl: "./uma-portraits/haru-urara.png" },
  {
    id: "54",
    name: "Matifuku",
    imageUrl: "./uma-portraits/matikanefukukitaru.png",
  },
  {
    id: "55",
    name: "Nice Nature",
    imageUrl: "./uma-portraits/nice-nature.png",
  },
  { id: "56", name: "King Halo", imageUrl: "./uma-portraits/king-halo.png" },
  {
    id: "57",
    name: "Mejiro Dober",
    imageUrl: "./uma-portraits/mejiro-dober.png",
  },
];

// Race tracks with distances and surfaces
// TODO: Fill in complete distance/surface data for each track
export const SAMPLE_MAPS: Map[] = [
  // Sapporo
  {
    id: "sapporo-1200-turf",
    track: "Sapporo",
    distance: 1200,
    surface: "Turf",
    name: "Sapporo - 1200m Turf",
  },
  {
    id: "sapporo-1500-turf",
    track: "Sapporo",
    distance: 1500,
    surface: "Turf",
    name: "Sapporo - 1500m Turf",
  },
  {
    id: "sapporo-1800-turf",
    track: "Sapporo",
    distance: 1800,
    surface: "Turf",
    name: "Sapporo - 1800m Turf",
  },
  {
    id: "sapporo-2000-turf",
    track: "Sapporo",
    distance: 2000,
    surface: "Turf",
    name: "Sapporo - 2000m Turf",
  },
  {
    id: "sapporo-2600-turf",
    track: "Sapporo",
    distance: 2600,
    surface: "Turf",
    name: "Sapporo - 2600m Turf",
  },
  {
    id: "sapporo-1000-dirt",
    track: "Sapporo",
    distance: 1000,
    surface: "Dirt",
    name: "Sapporo - 1000m Dirt",
  },
  {
    id: "sapporo-1700-dirt",
    track: "Sapporo",
    distance: 1700,
    surface: "Dirt",
    name: "Sapporo - 1700m Dirt",
  },
  {
    id: "sapporo-2400-dirt",
    track: "Sapporo",
    distance: 2400,
    surface: "Dirt",
    name: "Sapporo - 2400m Dirt",
  },

  // Hakodate
  {
    id: "hakodate-1000-turf",
    track: "Hakodate",
    distance: 1000,
    surface: "Turf",
    name: "Hakodate - 1000m Turf",
  },
  {
    id: "hakodate-1200-turf",
    track: "Hakodate",
    distance: 1200,
    surface: "Turf",
    name: "Hakodate - 1200m Turf",
  },
  {
    id: "hakodate-1800-turf",
    track: "Hakodate",
    distance: 1800,
    surface: "Turf",
    name: "Hakodate - 1800m Turf",
  },
  {
    id: "hakodate-2000-turf",
    track: "Hakodate",
    distance: 2000,
    surface: "Turf",
    name: "Hakodate - 2000m Turf",
  },
  {
    id: "hakodate-2600-turf",
    track: "Hakodate",
    distance: 2600,
    surface: "Turf",
    name: "Hakodate - 2600m Turf",
  },
  {
    id: "hakodate-1000-dirt",
    track: "Hakodate",
    distance: 1000,
    surface: "Dirt",
    name: "Hakodate - 1000m Dirt",
  },
  {
    id: "hakodate-1700-dirt",
    track: "Hakodate",
    distance: 1700,
    surface: "Dirt",
    name: "Hakodate - 1700m Dirt",
  },
  {
    id: "hakodate-2400-dirt",
    track: "Hakodate",
    distance: 2400,
    surface: "Dirt",
    name: "Hakodate - 2400m Dirt",
  },

  // Niigata
  {
    id: "niigata-1000-turf",
    track: "Niigata",
    distance: 1000,
    surface: "Turf",
    name: "Niigata - 1000m Turf",
  },
  {
    id: "niigata-1200-turf-inner",
    track: "Niigata",
    distance: 1200,
    surface: "Turf",
    variant: "Inner",
    name: "Niigata - 1200m Turf (Inner)",
  },
  {
    id: "niigata-1400-turf-inner",
    track: "Niigata",
    distance: 1400,
    surface: "Turf",
    variant: "Inner",
    name: "Niigata - 1400m Turf (Inner)",
  },
  {
    id: "niigata-1600-turf-outer",
    track: "Niigata",
    distance: 1600,
    surface: "Turf",
    variant: "Outer",
    name: "Niigata - 1600m Turf (Outer)",
  },
  {
    id: "niigata-1800-turf-outer",
    track: "Niigata",
    distance: 1800,
    surface: "Turf",
    variant: "Outer",
    name: "Niigata - 1800m Turf (Outer)",
  },
  {
    id: "niigata-2000-turf-inner",
    track: "Niigata",
    distance: 2000,
    surface: "Turf",
    variant: "Inner",
    name: "Niigata - 2000m Turf (Inner)",
  },
  {
    id: "niigata-2000-turf-outer",
    track: "Niigata",
    distance: 2000,
    surface: "Turf",
    variant: "Outer",
    name: "Niigata - 2000m Turf (Outer)",
  },
  {
    id: "niigata-2200-turf-inner",
    track: "Niigata",
    distance: 2200,
    surface: "Turf",
    variant: "Inner",
    name: "Niigata - 2200m Turf (Inner)",
  },
  {
    id: "niigata-2400-turf-inner",
    track: "Niigata",
    distance: 2400,
    surface: "Turf",
    variant: "Inner",
    name: "Niigata - 2400m Turf (Inner)",
  },
  {
    id: "niigata-1200-dirt",
    track: "Niigata",
    distance: 1200,
    surface: "Dirt",
    name: "Niigata - 1200m Dirt",
  },
  {
    id: "niigata-1800-dirt",
    track: "Niigata",
    distance: 1800,
    surface: "Dirt",
    name: "Niigata - 1800m Dirt",
  },
  {
    id: "niigata-2500-dirt",
    track: "Niigata",
    distance: 2500,
    surface: "Dirt",
    name: "Niigata - 2500m Dirt",
  },

  // Fukushima
  {
    id: "fukushima-1200-turf",
    track: "Fukushima",
    distance: 1200,
    surface: "Turf",
    name: "Fukushima - 1200m Turf",
  },
  {
    id: "fukushima-1800-turf",
    track: "Fukushima",
    distance: 1800,
    surface: "Turf",
    name: "Fukushima - 1800m Turf",
  },
  {
    id: "fukushima-2000-turf",
    track: "Fukushima",
    distance: 2000,
    surface: "Turf",
    name: "Fukushima - 2000m Turf",
  },
  {
    id: "fukushima-2600-turf",
    track: "Fukushima",
    distance: 2600,
    surface: "Turf",
    name: "Fukushima - 2600m Turf",
  },
  {
    id: "fukushima-1150-dirt",
    track: "Fukushima",
    distance: 1150,
    surface: "Dirt",
    name: "Fukushima - 1150m Dirt",
  },
  {
    id: "fukushima-1700-dirt",
    track: "Fukushima",
    distance: 1700,
    surface: "Dirt",
    name: "Fukushima - 1700m Dirt",
  },
  {
    id: "fukushima-2400-dirt",
    track: "Fukushima",
    distance: 2400,
    surface: "Dirt",
    name: "Fukushima - 2400m Dirt",
  },

  // Nakayama
  {
    id: "nakayama-1200-turf-outer",
    track: "Nakayama",
    distance: 1200,
    surface: "Turf",
    variant: "Outer",
    name: "Nakayama - 1200m Turf (Outer)",
  },
  {
    id: "nakayama-1600-turf-outer",
    track: "Nakayama",
    distance: 1600,
    surface: "Turf",
    variant: "Outer",
    name: "Nakayama - 1600m Turf (Outer)",
  },
  {
    id: "nakayama-1800-turf-inner",
    track: "Nakayama",
    distance: 1800,
    surface: "Turf",
    variant: "Inner",
    name: "Nakayama - 1800m Turf (Inner)",
  },
  {
    id: "nakayama-2000-turf-inner",
    track: "Nakayama",
    distance: 2000,
    surface: "Turf",
    variant: "Inner",
    name: "Nakayama - 2000m Turf (Inner)",
  },
  {
    id: "nakayama-2200-turf-outer",
    track: "Nakayama",
    distance: 2200,
    surface: "Turf",
    variant: "Outer",
    name: "Nakayama - 2200m Turf (Outer)",
  },
  {
    id: "nakayama-2500-turf-inner",
    track: "Nakayama",
    distance: 2500,
    surface: "Turf",
    variant: "Inner",
    name: "Nakayama - 2500m Turf (Inner)",
  },
  {
    id: "nakayama-3600-turf-inner",
    track: "Nakayama",
    distance: 3600,
    surface: "Turf",
    variant: "Inner",
    name: "Nakayama - 3600m Turf (Inner)",
  },
  {
    id: "nakayama-1200-dirt",
    track: "Nakayama",
    distance: 1200,
    surface: "Dirt",
    name: "Nakayama - 1200m Dirt",
  },
  {
    id: "nakayama-1800-dirt",
    track: "Nakayama",
    distance: 1800,
    surface: "Dirt",
    name: "Nakayama - 1800m Dirt",
  },
  {
    id: "nakayama-2400-dirt",
    track: "Nakayama",
    distance: 2400,
    surface: "Dirt",
    name: "Nakayama - 2400m Dirt",
  },
  {
    id: "nakayama-2500-dirt",
    track: "Nakayama",
    distance: 2500,
    surface: "Dirt",
    name: "Nakayama - 2500m Dirt",
  },

  // Tokyo
  {
    id: "tokyo-1400-turf",
    track: "Tokyo",
    distance: 1400,
    surface: "Turf",
    name: "Tokyo - 1400m Turf",
  },
  {
    id: "tokyo-1600-turf",
    track: "Tokyo",
    distance: 1600,
    surface: "Turf",
    name: "Tokyo - 1600m Turf",
  },
  {
    id: "tokyo-1800-turf",
    track: "Tokyo",
    distance: 1800,
    surface: "Turf",
    name: "Tokyo - 1800m Turf",
  },
  {
    id: "tokyo-2000-turf",
    track: "Tokyo",
    distance: 2000,
    surface: "Turf",
    name: "Tokyo - 2000m Turf",
  },
  {
    id: "tokyo-2300-turf",
    track: "Tokyo",
    distance: 2300,
    surface: "Turf",
    name: "Tokyo - 2300m Turf",
  },
  {
    id: "tokyo-2400-turf",
    track: "Tokyo",
    distance: 2400,
    surface: "Turf",
    name: "Tokyo - 2400m Turf",
  },
  {
    id: "tokyo-2500-turf",
    track: "Tokyo",
    distance: 2500,
    surface: "Turf",
    name: "Tokyo - 2500m Turf",
  },
  {
    id: "tokyo-3400-turf",
    track: "Tokyo",
    distance: 3400,
    surface: "Turf",
    name: "Tokyo - 3400m Turf",
  },
  {
    id: "tokyo-1300-dirt",
    track: "Tokyo",
    distance: 1300,
    surface: "Dirt",
    name: "Tokyo - 1300m Dirt",
  },
  {
    id: "tokyo-1400-dirt",
    track: "Tokyo",
    distance: 1400,
    surface: "Dirt",
    name: "Tokyo - 1400m Dirt",
  },
  {
    id: "tokyo-1600-dirt",
    track: "Tokyo",
    distance: 1600,
    surface: "Dirt",
    name: "Tokyo - 1600m Dirt",
  },
  {
    id: "tokyo-2100-dirt",
    track: "Tokyo",
    distance: 2100,
    surface: "Dirt",
    name: "Tokyo - 2100m Dirt",
  },
  {
    id: "tokyo-2400-dirt",
    track: "Tokyo",
    distance: 2400,
    surface: "Dirt",
    name: "Tokyo - 2400m Dirt",
  },

  // Chukyo
  {
    id: "chukyo-1200-turf",
    track: "Chukyo",
    distance: 1200,
    surface: "Turf",
    name: "Chukyo - 1200m Turf",
  },
  {
    id: "chukyo-1400-turf",
    track: "Chukyo",
    distance: 1400,
    surface: "Turf",
    name: "Chukyo - 1400m Turf",
  },
  {
    id: "chukyo-1600-turf",
    track: "Chukyo",
    distance: 1600,
    surface: "Turf",
    name: "Chukyo - 1600m Turf",
  },
  {
    id: "chukyo-2000-turf",
    track: "Chukyo",
    distance: 2000,
    surface: "Turf",
    name: "Chukyo - 2000m Turf",
  },
  {
    id: "chukyo-2200-turf",
    track: "Chukyo",
    distance: 2200,
    surface: "Turf",
    name: "Chukyo - 2200m Turf",
  },
  {
    id: "chukyo-1200-dirt",
    track: "Chukyo",
    distance: 1200,
    surface: "Dirt",
    name: "Chukyo - 1200m Dirt",
  },
  {
    id: "chukyo-1400-dirt",
    track: "Chukyo",
    distance: 1400,
    surface: "Dirt",
    name: "Chukyo - 1400m Dirt",
  },
  {
    id: "chukyo-1800-dirt",
    track: "Chukyo",
    distance: 1800,
    surface: "Dirt",
    name: "Chukyo - 1800m Dirt",
  },
  {
    id: "chukyo-1900-dirt",
    track: "Chukyo",
    distance: 1900,
    surface: "Dirt",
    name: "Chukyo - 1900m Dirt",
  },

  // Kyoto
  {
    id: "kyoto-1200-turf-inner",
    track: "Kyoto",
    distance: 1200,
    surface: "Turf",
    variant: "Inner",
    name: "Kyoto - 1200m Turf (Inner)",
  },
  {
    id: "kyoto-1400-turf-inner",
    track: "Kyoto",
    distance: 1400,
    surface: "Turf",
    variant: "Inner",
    name: "Kyoto - 1400m Turf (Inner)",
  },
  {
    id: "kyoto-1400-turf-outer",
    track: "Kyoto",
    distance: 1400,
    surface: "Turf",
    variant: "Outer",
    name: "Kyoto - 1400m Turf (Outer)",
  },
  {
    id: "kyoto-1600-turf-inner",
    track: "Kyoto",
    distance: 1600,
    surface: "Turf",
    variant: "Inner",
    name: "Kyoto - 1600m Turf (Inner)",
  },
  {
    id: "kyoto-1600-turf-outer",
    track: "Kyoto",
    distance: 1600,
    surface: "Turf",
    variant: "Outer",
    name: "Kyoto - 1600m Turf (Outer)",
  },
  {
    id: "kyoto-1800-turf-outer",
    track: "Kyoto",
    distance: 1800,
    surface: "Turf",
    variant: "Outer",
    name: "Kyoto - 1800m Turf (Outer)",
  },
  {
    id: "kyoto-2000-turf-inner",
    track: "Kyoto",
    distance: 2000,
    surface: "Turf",
    variant: "Inner",
    name: "Kyoto - 2000m Turf (Inner)",
  },
  {
    id: "kyoto-2200-turf-outer",
    track: "Kyoto",
    distance: 2200,
    surface: "Turf",
    variant: "Outer",
    name: "Kyoto - 2200m Turf (Outer)",
  },
  {
    id: "kyoto-2400-turf-outer",
    track: "Kyoto",
    distance: 2400,
    surface: "Turf",
    variant: "Outer",
    name: "Kyoto - 2400m Turf (Outer)",
  },
  {
    id: "kyoto-3000-turf-outer",
    track: "Kyoto",
    distance: 3000,
    surface: "Turf",
    variant: "Outer",
    name: "Kyoto - 3000m Turf (Outer)",
  },
  {
    id: "kyoto-3200-turf-outer",
    track: "Kyoto",
    distance: 3200,
    surface: "Turf",
    variant: "Outer",
    name: "Kyoto - 3200m Turf (Outer)",
  },
  {
    id: "kyoto-1200-dirt",
    track: "Kyoto",
    distance: 1200,
    surface: "Dirt",
    name: "Kyoto - 1200m Dirt",
  },
  {
    id: "kyoto-1400-dirt",
    track: "Kyoto",
    distance: 1400,
    surface: "Dirt",
    name: "Kyoto - 1400m Dirt",
  },
  {
    id: "kyoto-1800-dirt",
    track: "Kyoto",
    distance: 1800,
    surface: "Dirt",
    name: "Kyoto - 1800m Dirt",
  },
  {
    id: "kyoto-1900-dirt",
    track: "Kyoto",
    distance: 1900,
    surface: "Dirt",
    name: "Kyoto - 1900m Dirt",
  },

  // Hanshin
  {
    id: "hanshin-1200-turf-inner",
    track: "Hanshin",
    distance: 1200,
    surface: "Turf",
    variant: "Inner",
    name: "Hanshin - 1200m Turf (Inner)",
  },
  {
    id: "hanshin-1400-turf-inner",
    track: "Hanshin",
    distance: 1400,
    surface: "Turf",
    variant: "Inner",
    name: "Hanshin - 1400m Turf (Inner)",
  },
  {
    id: "hanshin-1600-turf-outer",
    track: "Hanshin",
    distance: 1600,
    surface: "Turf",
    variant: "Outer",
    name: "Hanshin - 1600m Turf (Outer)",
  },
  {
    id: "hanshin-1800-turf-outer",
    track: "Hanshin",
    distance: 1800,
    surface: "Turf",
    variant: "Outer",
    name: "Hanshin - 1800m Turf (Outer)",
  },
  {
    id: "hanshin-2000-turf-inner",
    track: "Hanshin",
    distance: 2000,
    surface: "Turf",
    variant: "Inner",
    name: "Hanshin - 2000m Turf (Inner)",
  },
  {
    id: "hanshin-2200-turf-inner",
    track: "Hanshin",
    distance: 2200,
    surface: "Turf",
    variant: "Inner",
    name: "Hanshin - 2200m Turf (Inner)",
  },
  {
    id: "hanshin-2400-turf-outer",
    track: "Hanshin",
    distance: 2400,
    surface: "Turf",
    variant: "Outer",
    name: "Hanshin - 2400m Turf (Outer)",
  },
  {
    id: "hanshin-2600-turf-outer",
    track: "Hanshin",
    distance: 2600,
    surface: "Turf",
    variant: "Outer",
    name: "Hanshin - 2600m Turf (Outer)",
  },
  {
    id: "hanshin-3000-turf-inner",
    track: "Hanshin",
    distance: 3000,
    surface: "Turf",
    variant: "Inner",
    name: "Hanshin - 3000m Turf (Inner)",
  },
  {
    id: "hanshin-3200-turf-outer-to-inner",
    track: "Hanshin",
    distance: 3200,
    surface: "Turf",
    variant: "Outer to Inner",
    name: "Hanshin - 3200m Turf (Outer to Inner)",
  },
  {
    id: "hanshin-1200-dirt",
    track: "Hanshin",
    distance: 1200,
    surface: "Dirt",
    name: "Hanshin - 1200m Dirt",
  },
  {
    id: "hanshin-1400-dirt",
    track: "Hanshin",
    distance: 1400,
    surface: "Dirt",
    name: "Hanshin - 1400m Dirt",
  },
  {
    id: "hanshin-1800-dirt",
    track: "Hanshin",
    distance: 1800,
    surface: "Dirt",
    name: "Hanshin - 1800m Dirt",
  },
  {
    id: "hanshin-2000-dirt",
    track: "Hanshin",
    distance: 2000,
    surface: "Dirt",
    name: "Hanshin - 2000m Dirt",
  },

  // Kokura
  {
    id: "kokura-1200-turf",
    track: "Kokura",
    distance: 1200,
    surface: "Turf",
    name: "Kokura - 1200m Turf",
  },
  {
    id: "kokura-1800-turf",
    track: "Kokura",
    distance: 1800,
    surface: "Turf",
    name: "Kokura - 1800m Turf",
  },
  {
    id: "kokura-2000-turf",
    track: "Kokura",
    distance: 2000,
    surface: "Turf",
    name: "Kokura - 2000m Turf",
  },
  {
    id: "kokura-2600-turf",
    track: "Kokura",
    distance: 2600,
    surface: "Turf",
    name: "Kokura - 2600m Turf",
  },
  {
    id: "kokura-1000-dirt",
    track: "Kokura",
    distance: 1000,
    surface: "Dirt",
    name: "Kokura - 1000m Dirt",
  },
  {
    id: "kokura-1700-dirt",
    track: "Kokura",
    distance: 1700,
    surface: "Dirt",
    name: "Kokura - 1700m Dirt",
  },
  {
    id: "kokura-2400-dirt",
    track: "Kokura",
    distance: 2400,
    surface: "Dirt",
    name: "Kokura - 2400m Dirt",
  },

  // Ooi
  {
    id: "ooi-1200-dirt",
    track: "Ooi",
    distance: 1200,
    surface: "Dirt",
    name: "Ooi - 1200m Dirt",
  },
  {
    id: "ooi-1800-dirt",
    track: "Ooi",
    distance: 1800,
    surface: "Dirt",
    name: "Ooi - 1800m Dirt",
  },
  {
    id: "ooi-2000-dirt",
    track: "Ooi",
    distance: 2000,
    surface: "Dirt",
    name: "Ooi - 2000m Dirt",
  },

  // Kawasaki
  {
    id: "kawasaki-1400-dirt",
    track: "Kawasaki",
    distance: 1400,
    surface: "Dirt",
    name: "Kawasaki - 1400m Dirt",
  },
  {
    id: "kawasaki-1600-dirt",
    track: "Kawasaki",
    distance: 1600,
    surface: "Dirt",
    name: "Kawasaki - 1600m Dirt",
  },
  {
    id: "kawasaki-2100-dirt",
    track: "Kawasaki",
    distance: 2100,
    surface: "Dirt",
    name: "Kawasaki - 2100m Dirt",
  },

  // Funabashi
  {
    id: "funabashi-1000-dirt",
    track: "Funabashi",
    distance: 1000,
    surface: "Dirt",
    name: "Funabashi - 1000m Dirt",
  },
  {
    id: "funabashi-1600-dirt",
    track: "Funabashi",
    distance: 1600,
    surface: "Dirt",
    name: "Funabashi - 1600m Dirt",
  },
  {
    id: "funabashi-1800-dirt",
    track: "Funabashi",
    distance: 1800,
    surface: "Dirt",
    name: "Funabashi - 1800m Dirt",
  },
  {
    id: "funabashi-2400-dirt",
    track: "Funabashi",
    distance: 2400,
    surface: "Dirt",
    name: "Funabashi - 2400m Dirt",
  },

  // Morioka
  {
    id: "morioka-1200-dirt",
    track: "Morioka",
    distance: 1200,
    surface: "Dirt",
    name: "Morioka - 1200m Dirt",
  },
  {
    id: "morioka-1600-dirt",
    track: "Morioka",
    distance: 1600,
    surface: "Dirt",
    name: "Morioka - 1600m Dirt",
  },
  {
    id: "morioka-1800-dirt",
    track: "Morioka",
    distance: 1800,
    surface: "Dirt",
    name: "Morioka - 1800m Dirt",
  },
  {
    id: "morioka-2000-dirt",
    track: "Morioka",
    distance: 2000,
    surface: "Dirt",
    name: "Morioka - 2000m Dirt",
  },
];
